name: nrn-rrn
channels:
  - conda-forge
  - defaults
dependencies:
  - click=7.1.2
  - fiona=1.8.18
  - gdal=3.1.4
  - geopandas=0.8.1
  - networkx=2.3
  - numpy=1.19.4
  - pandas=1.1.4
  - python=3.6.11
  - pyyaml=5.3.1
  - requests=2.25.0
  - scipy=1.5.3
  - shapely=1.7.1
  - tqdm=4.53.0
